# docker-compose.yml

version: '3.8'

services:
  sam:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - .:/var/task
      - /var/run/docker.sock:/var/run/docker.sock
    command: >
      sam local start-api
      --host 0.0.0.0
      --debug
      --template template.yaml

  email-test:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    command: node dist/functions/handlers/emailHandler.js

  geolocation-test:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    command: node scripts/test-geolocation.js
