AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Integreat API Stack (.env-based local dev)

Parameters:
  PaymongoSecretKey:
    Type: String
    Description: PayMongo Secret API Key
  SupabaseUrl:
    Type: String
    Description: Supabase URL
  SupabaseKey:
    Type: String
    Description: Supabase Key
  PhilSmsApiUrl:
    Type: String
    Description: PHIL SMS API URL
  PhilSmsApiKey:
    Type: String
    Description: PHIL SMS API Key
  SesEmailSender:
    Type: String
    Description: SES Sender Email
  NeonDbUrl:
    Type: String
    Description: Neon DB URL
  GoogleMapsApiKey:
    Type: String
    Description: Google Maps API Key

Globals:
  Function:
    Timeout: 30
    MemorySize: 128
    Runtime: nodejs18.x
    Environment:
      Variables:
        SUPABASE_URL: !Ref SupabaseUrl
        SUPABASE_KEY: !Ref SupabaseKey
        PHIL_SMS_API_URL: !Ref PhilSmsApiUrl
        PHIL_SMS_API_KEY: !Ref PhilSmsApiKey
        SES_SENDER_EMAIL: !Ref SesEmailSender
        NEON_DB_URL: !Ref NeonDbUrl
        PAYMONGO_SECRET_KEY: !Ref PaymongoSecretKey
        NODE_ENV: production

Resources:
  EmailFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: functions/handlers/emailHandler.handler
      Runtime: nodejs18.x
      CodeUri: ./dist
      Environment:
        Variables:
          NODE_ENV: development
          SUPABASE_URL: !Ref SupabaseUrl
          SUPABASE_KEY: !Ref SupabaseKey
          SES_SENDER_EMAIL: !Ref SesEmailSender
          NEON_DB_URL: !Ref NeonDbUrl
          AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1'
      Events:
        TestEvent:
          Type: Api
          Properties:
            Path: /email/send
            Method: post
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - ses:SendEmail
                - ses:SendRawEmail
              Resource: '*'

  SmsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: functions/handlers/smsHandler.handler
      Runtime: nodejs18.x
      CodeUri: ./dist
      Environment:
        Variables:
          NODE_ENV: development
          SUPABASE_URL: !Ref SupabaseUrl
          SUPABASE_KEY: !Ref SupabaseKey
          PHIL_SMS_API_URL: !Ref PhilSmsApiUrl
          PHIL_SMS_API_KEY: !Ref PhilSmsApiKey
          NEON_DB_URL: !Ref NeonDbUrl
          AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1'
      Events:
        TestEvent:
          Type: Api
          Properties:
            Path: /sms/send
            Method: post

  GeolocationFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: functions/handlers/geolocationHandler.handler
      Runtime: nodejs18.x
      CodeUri: ./dist
      Environment:
        Variables:
          NODE_ENV: development
          SUPABASE_URL: !Ref SupabaseUrl
          SUPABASE_KEY: !Ref SupabaseKey
          GOOGLE_MAPS_API_KEY: !Ref GoogleMapsApiKey
          NEON_DB_URL: !Ref NeonDbUrl
          AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1'
      Events:
        TestEvent:
          Type: Api
          Properties:
            Path: /maps/geocode
            Method: get

  PaymentFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: functions/handlers/paymentHandler.handler
      Runtime: nodejs18.x
      CodeUri: ./dist
      Environment:
        Variables:
          NODE_ENV: development
          SUPABASE_URL: !Ref SupabaseUrl
          SUPABASE_KEY: !Ref SupabaseKey
          NEON_DB_URL: !Ref NeonDbUrl
          PAYMONGO_SECRET_KEY: !Ref PaymongoSecretKey
          AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1'
      Events:
        TestEvent:
          Type: Api
          Properties:
            Path: /payment/create
            Method: post
